### ISSUE TITLE
too much dependencies ?

### ISSUE THREAD

**Issue by SebCanet** [philippejadin/arduino-cli-agent#1]
Hi,
thanks for this work on arduino-cli. I tried but I have a problem with tkinter.
Is it necessary to install so many modules ? Can we have a 'light' version please ?
Many thanks.

**Comment by philippejadin** [comment]
I just pushed a new version without this dependency. It should be light. In order to test, check the readme it's not accurate. I still need to check if it works on windows (correct path to arduino-cli.exe)

**Comment by SebCanet** [comment]
I could test in few days I think. But as I know nothing in Python programming, I can't help but here is a project from a Blockly@rduino's contributor: https://github.com/nbremond77/rDuino-Compiler-Uploader-Server
Maybe this could help...

**Comment by philippejadin** [comment]
I'll release something working probably today. I keep both versions, but I start to quite like nodejs to be honest :-) I can make binaries for the 3 platform (windows, linux, mac) with a simple command line, and it works well.

I'll post here when it's ready.

**Comment by philippejadin** [comment]
first exe to test here : https://github.com/philippejadin/arduino-cli-agent/releases/tag/0.1

Beside, I added some more docs in the readme

**Comment by philippejadin** [comment]
I just updated the exe. It now donwloads arduino-cli automatically for you. This one should be already quite fail proof :-)

**Comment by SebCanet** [comment]
Doesn't work on Windows 7 x64. Connected through nothing....no proxy.

![pb](https://user-images.githubusercontent.com/6362199/51134537-2df86700-1838-11e9-8006-f50f234f610b.jpg)

**Comment by philippejadin** [comment]
Yes, I managed to introduce a bug in the latest attempt. 
What would be the best way to distribute the arduino-cli binary do you think? Provide everything (start.exe + arduino-cli.exe) in a zip file ?

**Comment by SebCanet** [comment]
I think it's easier for newbies...a complete package to start maybe ?
I think an installer with donwloading elements would be useful when everything will be ok.

**Comment by philippejadin** [comment]
can you try once more? Now there is a zip file. Still need to add the examples folder but this can be downloaded from git (just for testing). Thanks!

**Comment by SebCanet** [comment]
Works well, also detected my 2 arduino 'unknwon' type...and cannot force it.
Could it be possible to send it as argument from Blockly@rduino ?

**Comment by philippejadin** [comment]
I create separate issues for those questions and close this one :-)
